services:
  db:
    image: postgres:16 # Use a specific version, e.g., PostgreSQL 16
    container_name: nd-rust-db
    restart: unless-stopped
    environment:
      # Rely solely on .env file for these values
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      # Map container port 5432 to host port 5433 to avoid conflicts
      - "5433:5432"
    volumes:
      # Persist database data locally in a named volume
      - nd_rust_postgres_data:/var/lib/postgresql/data
      # Remove the init-db script mount for now
      # - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-test_user} -d $${POSTGRES_DB:-nd_rust_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Add the main application service later if needed for full containerized dev
  # app:
  #   build: .
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   environment:
  #     DATABASE_URL: "postgres://${POSTGRES_USER:-test_user}:${POSTGRES_PASSWORD:-test_password}@db/${POSTGRES_DB:-nd_rust_db}" 
  #     RUST_LOG: "info,nd_rust=debug,web=debug"
  #   ports:
  #     - "3000:3000"

volumes:
  nd_rust_postgres_data:
    driver: local 